config/routes.rb
YouCloth::Application.routes.draw do

  namespace :admin do 
    resources :dashboard
    resources :posts  do
      resources :comments do
        post :reply, :on => :member
      end
    end
  end

   match "you/washes/:id" => 'you#show', as: "you_washes"
   match 'you' => 'you#index'
  scope "/you" do
      resources :posts
   end

  resources :posts do
    resources :comments do
      post :reply
    end
  end

  resources :customers  do
    collection do
      get :users
      get :new_popup
      post :create_popup
    end
  end

  resources :washes do
    collection do
      get :customers
    end
  end

  resources :cloth_items

  resources :cloths

  resources :roles

  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" },
                      :path_names => { :sign_up => "register", 
                                      :sign_in => "login", 
                                      :sign_out => "logout",
                                      :settings => "settings" }
  devise_scope :user do
    post :change_customer, :to => "users/registrations#change_customer"
    put :change_customer, :to => "users/registrations#change_customer"
  end

  

  root :to => "home#index"
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates_presence_of :body
  validates_presence_of :user

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    c = self.new
    c.commentable_id = obj.id
    c.commentable_type = obj.class.base_class.name
    c.body = comment
    c.user_id = user_id
    c
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.size > 0
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/controllers/admin/comments_controller.rb
require 'comment'
class Admin::CommentsController < ApplicationController
  before_filter :authenticate_user!  
  filter_resource_access
  layout "admin"
  # GET /admin/comments
  # GET /admin/comments.json
  def index
    @commentable = find_commentable
     #@comments = @commentable.comment_threads #.first.root.self_and_descendants
    @root_comments = @commentable.root_comments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /admin/comments/1
  # GET /admin/comments/1.json
  def show
   @commentable = find_commentable
   @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_comment }
    end
  end

  # GET /admin/comments/new
  # GET /admin/comments/new.json
  def new
    @commentable = find_commentable
    @comment =  Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_comment }
    end
  end

  # GET /admin/comments/1/edit
  def edit
    @commentable = find_commentable
    @comment =  Comment.find(params[:id])
  end

  # POST /admin/comments
  # POST /admin/comments.json
  def create
    @commentable = find_commentable
    #@comment =  Comment.new(params[:comment])
    @comment = Comment.new(:user => current_user, :commentable =>@commentable, :body=>params[:comment][:body])

    respond_to do |format|
      if @comment.save
        @comment.commentable.update_attribute( :replies,@comment.commentable.comment_threads.size)
       
       format.html { redirect_to admin_post_comments_path(@commentable), notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @admin_comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/comments/1
  # PUT /admin/comments/1.json
  def update
    @commentable = find_commentable
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        @comment.commentable.touch

        format.html { redirect_to admin_post_comment_path(@commentable, @comment), notice: 'Comment was successfully created.' }
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/comments/1
  # DELETE /admin/comments/1.json
  def destroy
    @commentable = find_commentable
    @comment = Comment.find(params[:id])
    @comment.destroy
    @commentable.update_column( :replies,@commentable.comment_threads.size)

    respond_to do |format|
      format.html { redirect_to admin_post_comments_url(@commentable) }
      format.json { head :no_content }
    end
  end

  #POST /admin/posts/:post_id/comments/:comment_id/reply
  def reply
    @commentable = find_commentable('post')
    #@comment = find_commentable('comment')
    @comment = Comment.find(params[:id])
    @reply_comment = Comment.new( :user => current_user, :commentable =>@commentable, :body=>params[:comment][:body])
    #@reply_comment = Comment.new(:user => current_user,  :body=>params[:comment][:body])
     respond_to do |format|
        #@reply_comment.commentable.replies += 1
        @reply_comment.commentable.replies = @reply_comment.commentable.comment_threads.size
       if @reply_comment.save
            @reply_comment.move_to_child_of( @comment)
            #p @comment.to_text
            #@reply_comment.commentable.touch
            # update_attribute: updated_at/updated_on column is updated if that column is available.
            @reply_comment.commentable.update_attribute( :replies,@reply_comment.commentable.comment_threads.size)

            format.html { redirect_to admin_post_comments_path(@commentable), notice: 'Comment was successfully created.'}
        else
          format.html {render action: "new", notice: 'Comment was not created.'}
        end
     end
  end

   protected

  def find_commentable(name=nil)  
    if name.nil?
      params.each do |name, value|  
        if name =~ /(.+)_id$/  
          return $1.classify.constantize.find(value)  
        end  
      end
    else
      return name.classify.constantize.find(params[(name+'_id').to_sym])
    end
    nil  
  end 
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!  
  # filter_resource_access :additional_collection => { :reply => :read }
  #filter_resource_access 

  # GET /posts/:post_id/comments
  # GET /posts/:post_id/comments.json
  def index
    #@comments = Comment.all
    @commentable = find_commentable
    #p @commentable.root_comments
    #@comments = @commentable.comment_threads #.first.root.self_and_descendants
    @root_comments = @commentable.root_comments
    #@commentable.increment!(:views)
    @commentable.class.increment_counter(:views, @commentable.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /posts/:post_id/comments/:id
  def show
    @commentable = find_commentable
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erbk the last migration, for example if you made a mistake in it and wish to correct it. Rather than tracking down the version number associated with
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    #@post = find_commentable
    @commentable = find_commentable
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    #@comment = Comment.new(params[:comment])
    @commentable = find_commentable
    #@comment = @commentable.comments.build( params[:comment])
    @comment = Comment.new(:user => current_user, :commentable =>@commentable, :body=>params[:comment][:body])
    respond_to do |format|
       if @comment.save
        #@comment.commentable.replies += 1
        # @comment.commentable.touch
        @comment.commentable.update_attribute( :replies,@comment.commentable.comment_threads.size)
       
        format.html { redirect_to :id => nil, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new", notice: 'Comment was not created.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  #POST /posts/:post_id/comments/:comment_id/reply
  def reply
    @commentable = find_commentable('post')
    @comment = find_commentable('comment')
    @reply_comment = Comment.new( :user => current_user, :commentable =>@commentable, :body=>params[:comment][:body])
    #@reply_comment = Comment.new(:user => current_user,  :body=>params[:comment][:body])
     respond_to do |format|
        #@reply_comment.commentable.replies += 1
        @reply_comment.commentable.replies = @reply_comment.commentable.comment_threads.size
       if @reply_comment.save
            @reply_comment.move_to_child_of( @comment)
            #p @comment.to_text
            #@reply_comment.commentable.touch
            # update_attribute: updated_at/updated_on column is updated if that column is available.
            @reply_comment.commentable.update_attribute( :replies,@reply_comment.commentable.comment_threads.size)

            format.html { redirect_to post_comments_path(@commentable), notice: 'Comment was successfully created.'}
        else
          format.html {render action: "new", notice: 'Comment was not created.'}
        end
     end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @commentable = find_commentable
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        @comment.commentable.touch
        
        format.html { redirect_to post_comments_path(@commentable), notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @commentable = find_commentable
    @comment = Comment.find(params[:id])
    @comment.destroy
    #@commentable.replies -= 1
    @commentable.update_column( :replies,@commentable.comment_threads.size)
    respond_to do |format|
      #format.html { redirect_to comments_url }
      format.html { redirect_to post_comments_path(@commentable) }
      format.json { head :no_content }
    end
  end

  protected

  def find_commentable(name=nil, user = current_user)  
    if name.nil?
      params.each do |name, value|  
        if name =~ /(.+)_id$/  
          return $1.classify.constantize.where("user_id = ?", user.id).find(value)  
        end  
      end
    else
      return name.classify.constantize.where("user_id = ?", user.id).find(params[(name+'_id').to_sym])
    end
    nil  
  end 

  # def find_commentable(name)
  #     return name.classify.constantize.find(params[(name+'_id').to_sym])
  # end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_form.html.erb
<%#= form_for  @comment, :url=> admin_post_comment_path(@commentable, @comment) do |f| %>
<%= form_for([:admin, @commentable, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>:
    <%= f.text_field :title, size: 58 %>
  </div>
  <div class="field">
    <%= f.text_area :body, cols: 68 %>
  </div>
   <br/>
  <div class="actions">
    <%= f.submit %> 
  </div>
<% end %>

app/views/admin/comments/edit.html.erb
<h1>Editing admin_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_post_comment_path(@commentable, @comment) %> |
<%= link_to 'Back', admin_post_comments_path( @commentable) %>

app/views/admin/comments/index.html.erb
<div id="list">
  <div>
    <b><%= @commentable.title %></b>
  </div>
  <div style="line-height:1.8em">
    <%=sanitize escape_precode word_wrap @commentable.body %>
  </div>
 <div style="color:#aadddd">  
    <spen><%= @commentable.updated_at %></spen>
    <spen>by <%= @commentable.user.email %></spen>
    <spen><%= link_to 'Edit', edit_admin_post_path(@commentable) %></spen>
    <spen><%= link_to 'Destroy', admin_post_path(@commentable), confirm: 'Are you sure?', method: :delete %></spen>
    <div><span><%= distance_of_time_in_words_to_now(@commentable.updated_at)%> 전</span>
      <span>Replies(<%= @commentable.replies %>)</span>
      <span>Views(<%= @commentable.views %>)</span>
    </div>
  </div>

  <h3>Listing comments</h3>
  <% @root_comments.each do |root| %>
    <% Comment.each_with_level( root.self_and_descendants) do |comment, level| %>
        <%= ('<div class="prefix_1">' * level).html_safe %>
        <hr/><%= comment.id %>:<%= comment.parent_id %>
        <div style="line-height:1.8em"> 
          <%= sanitize( escape_precode( word_wrap(comment.body))) %>
        </div>
      <div style="color:#aabbbb">  
        <spen><%= comment.updated_at %></spen>
        <spen>by <%= comment.user.email %></spen>
         <spen><%= link_to 'Reply', admin_post_comment_path(@commentable,comment) %></spen>
       <spen><%= link_to 'Edit', edit_admin_post_comment_path(@commentable,comment) %></spen>
        <spen><%= link_to 'Destroy', admin_post_comment_path(@commentable, comment), confirm: 'Are you sure?', method: :delete %></spen>
      </div>
     <%= ('</div>' * level).html_safe %> 
    <% end %>
  <% end %>

  <br />
  <h2>New Comment</h2>  
  <%= form_for Comment.new, :url => admin_post_comments_path(@commentable) do |f| %>  
    <div>  
        <%= f.label :body %> <br/> 
        <%= f.text_area :body, rows: 12, cols: 68  %>  
      </div>  
      <div><%= submit_tag "Add Comment" %> &nbsp; <%= link_to t('Back'), admin_posts_path %></div>  
   <% end %>  
</div>

app/views/admin/comments/new.html.erb
<h2>New admin comment</h2>

<%= render 'form' %>

<%= link_to 'Back', admin_post_comments_path(@post) %>

app/views/admin/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @comment.title %>
</p>

<p>
  <b>Body:</b>
  <%= sanitize escape_precode word_wrap @comment.body %>
</p>

<br />
<h2>Reply to Comment</h2>  
<%= form_for Comment.new, url: reply_admin_post_comment_path(@commentable, @comment)  do |f| %>  
 <div>  
      <%= f.label :body %> <br/> 
      <%= f.text_area :body, rows: 12, cols: 68  %>  
    </div>  
    <div><%= submit_tag "Add to Reply" %>
	<%= link_to 'Edit', edit_admin_post_comment_path(@commentable, @comment) %> |
	<%= link_to 'Back', admin_post_comments_path(@commentable) %>
   </div>  
  
<% end %>  