config/routes.rb
YouCloth::Application.routes.draw do

  namespace :admin do 
    resources :dashboard
    resources :posts  do
      resources :comments do
        post :reply, :on => :member
      end
    end
  end

   match "you/washes/:id" => 'you#show', as: "you_washes"
   match 'you' => 'you#index'
  scope "/you" do
      resources :posts
   end

  resources :posts do
    resources :comments do
      post :reply
    end
  end

  resources :customers  do
    collection do
      get :users
      get :new_popup
      post :create_popup
    end
  end

  resources :washes do
    collection do
      get :customers
    end
  end

  resources :cloth_items

  resources :cloths

  resources :roles

  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" },
                      :path_names => { :sign_up => "register", 
                                      :sign_in => "login", 
                                      :sign_out => "logout",
                                      :settings => "settings" }
  devise_scope :user do
    post :change_customer, :to => "users/registrations#change_customer"
    put :change_customer, :to => "users/registrations#change_customer"
  end

  

  root :to => "home#index"
  

end

app/models/wash.rb
class Wash < ActiveRecord::Base
  has_many :cloths,	:dependent => :destroy
  belongs_to :customer
end

app/controllers/washes_controller.rb
class WashesController < ApplicationController
   before_filter :authenticate_user!  
   filter_resource_access  :additional_collection => { :customers => :read }
    layout "admin"

  # GET /washes
  # GET /washes.json
  def index
    q = params[:q]
    field = params[:field]
    #logger.debug ">> field: #{field}"
    if q.blank?
      @washes = Wash.paginate(:page => params[:page]).order('stocked_on DESC, id ASC')
      #@washes = Wash.paginate :page => params[:page] || 1, :per_page => 2, :order => 'stocked_on DESC, created_at ASC'
    else
      q.strip!
      field.strip!
      @washes = case field.to_sym
                when :name
                  Wash.where(" LOWER(name) LIKE ? ", "%#{q.downcase}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                  #Wash.paginate :page => params[:page]||1, :per_page => 2,:conditions =>[" LOWER(name) LIKE ? ", "%#{q.downcase}%"],:order =>'stocked_on DESC, created_at ASC'
                when :email
                  Wash.where(" LOWER(email) LIKE ? ", "%#{q.downcase}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                  #Wash.paginate :page => params[:page]||1, :per_page => 2,:conditions =>[" LOWER(email) LIKE ? ", "%#{q.downcase}%"],:order =>'stocked_on DESC, created_at ASC'
                when :phone
                  Wash.where(" phone LIKE ? OR mobile LIKE ? ", "%#{q}%", "%#{q}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                  #Wash.paginate :page => params[:page]||1, :per_page => 2,:conditions =>[" phone LIKE ? OR mobile LIKE ? ", "%#{q}%", "%#{q}%"], :order =>'stocked_on DESC, created_at ASC'
                when :address
                  Wash.where(" LOWER(address) LIKE ? OR LOWER(address2) LIKE ? ", "%#{q.downcase}%", "%#{q.downcase}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                  #Wash.paginate :page => params[:page]||1, :per_page => 2,:conditions =>[" LOWER(address) LIKE ? OR LOWER(address2) LIKE ? ", "%#{q.downcase}%", "%#{q.downcase}%"],:order =>'stocked_on DESC, created_at ASC'
                when :stocked_on
                  Wash.where(" stocked_on LIKE ? ", "%#{q}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                  #Wash.paginate :page => params[:page]||1, :per_page => 2,:conditions =>[" stocked_on LIKE ? ", "%#{q}%"], :order =>'stocked_on DESC, created_at ASC'
                when :released_on
                  Wash.where(" released_on LIKE ? ", "%#{q}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                  #Wash.paginate :page => params[:page]||1, :per_page => 2,:conditions =>[" released_on LIKE ? ", "%#{q}%"], :order =>'stocked_on DESC, created_at ASC'
                when :status
                  Wash.where(" LOWER(status) LIKE ? ", "%#{q.downcase}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                  #Wash.paginate :page => params[:page]||1, :per_page => 2,:conditions =>[" LOWER(status) LIKE ? ", "%#{q.downcase}%"], :order =>'stocked_on DESC, created_at ASC'
                 when :customer_id
                  Wash.where(" customer_id = ? ", q).paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                else #all
                  where = <<-DOCUMENT
                    LOWER(name) LIKE ? OR LOWER(email) LIKE ? 
                    OR phone LIKE ? OR mobile LIKE ? 
                    OR LOWER(address) LIKE ? OR LOWER(address2) LIKE ?  
                    OR LOWER(status) LIKE ?  
                  DOCUMENT

                  Wash.where( where, "%#{q.downcase}%", "%#{q.downcase}%", "%#{q}%", "%#{q}%", "%#{q.downcase}%", "%#{q.downcase}%", "%#{q.downcase}%").paginate(:page => params[:page]).order('stocked_on DESC, id ASC')
                  #Wash.paginate :page => params[:page]||1, :per_page => 2,:conditions =>[ where, "%#{q.downcase}%", "%#{q.downcase}%", "%#{q}%", "%#{q}%", "%#{q.downcase}%", "%#{q.downcase}%", "%#{q}%", "%#{q}%"], :order =>'stocked_on DESC, created_at ASC'
                end
    end #end of if
    #@show_pagination = @washes.length > 0 && @washes.total_pages > 1
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @washes }
    end
  end

  # GET /washes/1
  # GET /washes/1.json
  def show
    @wash = Wash.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wash }
    end
  end

  # GET /washes/new
  # GET /washes/new.json
  def new
    @wash = Wash.new
    @cloth_items = ClothItem.all( :order  => :no)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wash }
    end
  end

  # GET /washes/1/edit
  def edit
    @wash = Wash.find(params[:id])
      #@cloth_items = ClothItem.all(:order => :no)
      #@cloth_items = ClothItem.includes(:cloth)
      #@cloth_items = ClothItem.joins(" LEFT OUTER JOIN cloths ON  cloths.cloth_item_id = cloth_items.id  AND  cloths.wash_id = #{params[:id]}")
    sql = <<-QUERY
          SELECT `cloth_items`.*, `cloths`.id AS cloth_id, `cloths`.unit_price AS cloth_unit_price,  
          `cloths`.count AS cloth_count, `cloths`.repair AS cloth_repair, 
          `cloths`.repair_price AS cloth_repair_price, `cloths`.status AS cloth_status  
          FROM `cloth_items` LEFT OUTER JOIN cloths ON cloths.cloth_item_id = cloth_items.id 
            AND cloths.wash_id =? 
          ORDER BY cloth_items.no
    QUERY
    @cloth_items = ClothItem.find_by_sql([sql, params[:id]])
  end

  # POST /washes
  # POST /washes.json
  def create
    @wash = Wash.new(params[:wash])
    @customer = Customer.find(@wash.customer_id)
    #local.attributes = remote.attributes.inject({}){|h,(k,v)| h[k]=v if Model.column_names.include?(k); h 
    @wash.attributes = @customer.attributes.inject({}){|h,(k,v)| h[k]=v if Wash.column_names.include?(k); h }
    @wash.updated_at = nil;
    @wash.created_at = nil;
    @wash.status = YouCloth::STATUSES[0]
    #TODO: attributes.delete
    #@wash.attributes.delete([:created_at, :updated_at])
    #@wash.created_at = nil
    #@wash.updated_at = nil    
    #@wash.created_at = Time.now
    #@wash.updated_at = Time.now
    #logger.debug ">> @wash.attributes: #{@wash.attributes.inspect}"

    respond_to do |format|
      if @wash.save
        #logger.debug ">> params[:cloth].length: #{params[:cloth].length}"
        #logger.debug ">> params[:cloth][0]: #{params[:cloth][0]}" 
        for i in 0...params[:cloth].length do
          @cloth = Cloth.new( params[:cloth][i])
          next  if @cloth.count.to_i < 1
          @cloth.wash_id = @wash.id
          @cloth.status = YouCloth::STATUSES[0]
          @cloth.save
        end  
        format.html { redirect_to @wash, notice: 'Wash was successfully created.' }
        format.json { render json: @wash, status: :created, location: @wash }
      else
        format.html { render action: "new" }
        format.json { render json: @wash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /washes/1
  # PUT /washes/1.json
  def update
    @wash = Wash.find(params[:id])

    respond_to do |format|
      if @wash.update_attributes(params[:wash])
        
        for i in 0...params[:cloth].length do
          cloth = Cloth.new( params[:cloth][i])
          cloth_id = params[:cloth][i][:id]
          #logger.debug ">> params[:cloth][#{i}][:id]: #{params[:cloth][i][:id]} "
          if cloth.count.to_i < 1
            Cloth.destroy(cloth_id) unless cloth_id.nil?
             next
           end
           
            if cloth_id.nil?
              #insert new record
              cloth.wash_id = @wash.id
              cloth.save 
              next
            end
            begin
              @cloth = Cloth.find(cloth_id)
              #@cloth.wash_id = @wash.id
              @cloth.update_attributes( params[:cloth][i])
            rescue  ActiveRecord::RecordNotFound => e
              logger.warn ">> RecordNotFound: #{e}"
              #insert new cloth
              #cloth.wash_id = @wash.id
              #cloth.save
            end
        end  # end of for
        
        format.html { redirect_to @wash, notice: 'Wash was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /washes/1
  # DELETE /washes/1.json
  def destroy
    @wash = Wash.find(params[:id])
    @wash.destroy

    respond_to do |format|
      format.html { redirect_to washes_url }
      format.json { head :no_content }
    end
  end
  
  def customers
    q = "%#{params[:q].downcase}%"
    logger.debug ">> q: #{q}"
    @customers = Customer.joins(:user).where(" LOWER(name) LIKE ?  OR  LOWER(users.email) LIKE ?  OR LOWER(mobile) LIKE ? OR LOWER(phone) LIKE ? OR LOWER(address) LIKE ? OR LOWER(address2) LIKE ? ", q, q, q, q, q, q).limit(20).order('name')
    respond_to do |format|
      format.html { render :partial =>  "washes/customers", :object => @customers }
     end
  end
end

app/helpers/washes_helper.rb
module WashesHelper
end

app/views/washes/_customers.html.erb
<table><thead>
<tr><td> Email(Roles) </td><td>name</td><td>Mobile</td><td>Phone</td><td>Address</td><td>Address2</td></tr>
</thead><tbody>
<% @customers.each do |customer| %>
<tr>
<td>
	<%= radio_button :wash, :customer_id, customer.id, :email =>customer.user.email %><%= customer.user.email %> (<%= customer.user.roles.map{ |r| r.name}.join(',') %>)
</td>
<td><%= customer.name %></td>
<td><%= customer.mobile %></td>
<td><%= customer.phone %></td>
<td><%= customer.address %></td>
<td><%= customer.address2 %></td>
</tr>
<% end %>
</tbody>
</table>
<div class="field">
	선택한 <%= label :wash, :email %> <br />
	<%= text_field :wash, :email, :readonly=> true %>
</div>

<script>
jQuery( function($){
  $("input:radio[name='wash[customer_id]']").click(function(){
      $("#wash_email").val($("input:radio[name='wash[customer_id]']:checked").attr('email'));
  });
});
</script>

app/views/washes/_form.html.erb
<%= form_for(@wash) do |f| %>
  <% if @wash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wash.errors.count, "error") %> prohibited this wash from being saved:</h2>

      <ul>
      <% @wash.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br />
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :registered_on %><br />
    <%= f.date_select :registered_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/washes/_newform.html.erb
<div id="list">
<div class="field">
  <%= label :customer, t(:search) %><br />
  <%= text_field_tag  :q %>  
  <button type="button" name="button" id="search_button"><%= t(:find_customer)%></button>
  <%= link_to t('new_customer'), new_popup_customers_path, :class=>"popup" %>
</div>
 
<%= form_for @wash do |f| %>
  <% if @wash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wash.errors.count, "error") %> prohibited this wash from being saved:</h2>
      <ul>
      <% @wash.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="customer_list"></div>
  <div class="field">
    <%= f.label t(:stocked_on) %><br />
    <%= f.date_select :stocked_on %>
  </div>
  <div class="field">
      <%= f.label t(:memo) %><br/>
      <%= f.text_area :memo, :rows =>5 %>
   </div>

 <table id="cloth_items_table"><thead>
 <tr><th>&nbsp;</th><th><%= t(:unit_price) %></th> <th><%= t(:count) %></th><th><%= t(:repair) %></th>  <th><%= t(:repair_price) %></th><th><%= t(:subtotal) %> </th>
 </tr>
 </thead>

 <tbody>
 <% @cloth_items.each  do | item | %>
   <%= hidden_field :cloth, :cloth_item_id, :index => nil, :value => item.id %>
 <tr><td class="right"><%= item.name %> </td>
   <td class="right unit_price"> <%=text_field :cloth, :unit_price, :index => nil,  :value => number_with_delimiter( item.unit_price, :delimiter => ",") , :onblur =>"number_format(this)", :onfocus =>"delete_number_delimiter(this)" , :class =>'right', :size =>4 %>원 </td>
 <td class="right count"> <%= text_field :cloth, :count, :index => nil, :class =>'right', :size =>2 %>개 </td>
 <td>  <%= text_field :cloth, :repair, :index => nil %> </td>
 <td>   <%= text_field :cloth, :repair_price, :index => nil, :size =>4, :class =>'right', :onblur =>"number_format(this)", :onfocus =>"delete_number_delimiter(this)" %>원 </td>
 <td> <%= text_field :cloth, :subtotal , :index => nil, :size =>6, :class =>'right',  :style=>"color:blue", :disabled=> true, :onblur =>"number_format(this)" %>원</td>
</tr>
 <% end %>
 </tbody>
 <tfoot><tr><td> </td><td class="right">총 개수:</td><td class="right"><span id="count_total"  style="color:red"></span></td>
    <td class="right"> 수선 합계/총 합계:</td><td class="right" ><span id="repair_price_total"  style="color:red"></span>/</td><td class="right"><span id="total"  style="color:red"></span></td> 
 </tr></tfoot>
 </table> 
 
  <div class="contentinfo">** 등록을 취소할 항목은 '개수 = 0 또는 공백' 을 입력하면 해당 항목은 등록되지 않습니다.<br/>
  ** 세탁은 하지 않고 수선만 할 경우 '세탁단가=0 또는 공백' 을 입력하고 '개수'값과 '수선가격'을 입력하면 수선 항목이 등록됩니다.
  </div> 
     
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div><!-- id=list -->

<script type="text/javascript">

 jQuery.noConflict();
  jQuery(document).ready(function($) {

       $("#search_button").click( function( ) {
        var q = $("#q").val();
       // alert(q);
        $.ajax({
          type: 'GET',
          url: '/washes/customers',
          data: { q:   q },
          success: function(data) {
          // alert( data);
           $("#customer_list").html( data);
          },
           error: function( data){ 
            // alert("error:#{data}");
             $("#customer_list").html(data);
           }
        });
        return false;
      });

      $('.popup').click(function() {
        var winProps='height=600,width=500,resizable=yes,scrollbars=yes';
        var newWin=open($(this).attr('href'),'aWin',winProps);
        newWin.focus();
        return false; 
      });   

       $('#new_wash').submit( function(){
          //alert($(":input:radio[name='wash[customer_id]']:checked").val());
          //alert($("#customer_list :input:radio[name='wash[customer_id]']:checked").val());
         if( !$("#customer_list :input:radio[name='wash[customer_id]']:checked").val()){
            alert('고객찾기로 찾은 고객을 선택하세요 ');
            $('#q').focus();
            return false;
          }
          return true;
      });

      var inputs = $('#cloth_items_table tbody tr td.unit_price input, #cloth_items_table tbody tr td.count input, #cloth_items_table tbody tr td #cloth__repair_price');
      var count_inputs = $('#cloth_items_table tbody tr td #cloth__count');
      var repair_price_inputs = $('#cloth_items_table tbody tr td #cloth__repair_price');
      var subtotal_inputs = $('#cloth_items_table tbody tr td #cloth__subtotal');
      //alert( subtotal_inputs.length);

       //inputs.change(function() {
      inputs.blur(function() {
       //alert('change');
        // Finding them this way purely so that we don't duplicate the code,
        // it would be faster to separate the inputs array into their type and bind the change appropriately.
        var unit_price = $(this).closest('tr').find('td #cloth__unit_price').val().replace(/[^\d\.]/g,'');
        var count = $(this).closest('tr').find('td #cloth__count').val().replace(/[^\d\.]/g,'');
        var repair_price = $(this).closest('tr').find('td #cloth__repair_price').val().replace(/[^\d\.]/g,'');
        var subtotal_input = $(this).closest('tr').find('td #cloth__subtotal');
        
        unit_price = isNaN(unit_price)? 0: unit_price * 1;
        count = isNaN(count)? 0: count * 1;
        repair_price = isNaN(repair_price)? 0: repair_price * 1;

        var subtotal = (count > 0)? unit_price * count + repair_price: 0;
        subtotal_input.val(subtotal.number_with_delimiter());
        //number_format( subtotal_input);

        update_totals();
      });
      
      function update_totals() {
        var  count_total = 0;
        var repair_total = 0;
        var total = 0;
        //alert("update_totals");
        $.each(count_inputs, function(){
          var val = parseInt($(this).val().replace(/[^\d\.]/g, ''));
          count_total +=  isNaN(val) ? 0: val;
         });
        $.each(repair_price_inputs, function(){
          var val = parseInt($(this).val().replace(/[^\d\.]/g, ''));
          repair_total +=  isNaN(val) ? 0: val;
        });
        $.each(subtotal_inputs, function(){
          var val = parseInt($(this).val().replace(/[^\d\.]/g, ''));
          total +=  isNaN(val) ? 0: val;
        });
      
        //alert( total);
        $("#count_total").html( count_total.number_with_delimiter() + '개');
        $("#repair_price_total").html( repair_total.number_with_delimiter() + '원');
        $("#total").text( total.number_with_delimiter() + '원');
        
      }    

    });  

</script>

app/views/washes/edit.html.erb
<div id="main" class="container_12" role="main">
  <div class="grid_12">

<h1>Editing wash</h1>

<%= render 'editform' %>

<%= link_to 'Show', @wash %> |
<%= link_to 'Back', washes_path %>
		
	</div><!-- class=grid_12 -->
</div><!-- class=container -->

app/views/washes/index.html.erb
  <div id="list">
  <%= form_tag washes_path, :method => :get  do %>
    <div class="field">
    <%= label :wash, t(:wash_search) %><br/>
    <%= select_tag 'field', options_for_select(YouCloth::WASH_SEARCH_FIELD, params[:field]) %> 
    <%= text_field_tag 'q', params[:q] %> 
    <%= submit_tag t(:find_wash) %>
    </div>
  <% end %>

  <h1><%= t(:listing_washes)%></h1>
   <%= link_to t(:new_wash), new_wash_path %>

    <div class="flickr_pagination">
      <%= will_paginate @washes, :container => false %>
      <div class='page_info'>(<%= page_entries_info @washes %>)</div>
    </div>

  <table>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Mobile/<br/>
          Phone</th>
      <th>Address</th>
      <th>Address2</th>
      <th>Stocked on</th>
      <th>Released on</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  <% @washes.each do |wash| %>
    <tr>
      <td><%= wash.id %></td>
      <td><%= link_to wash.name, washes_path(:field =>:customer_id, :q =>wash.customer_id) %></td>
      <td><%= link_to wash.email, washes_path(:field=>:email, :q=>wash.email) %></td>
      <td><%= wash.mobile %>/<br/>
          <%= wash.phone %></td>
      <td><%= wash.address %></td>
      <td><%= wash.address2 %></td>
      <td><%= link_to wash.stocked_on, washes_path(:field=>:stocked_on, :q=>wash.stocked_on) %><br/>
          <span style="font-size:small;color:#aaa"><%= distance_of_time_in_words_to_now(wash.stocked_on)%> 전</span></td>
      <td><%= wash.released_on %></td>
      <td><%= wash.status %></td>
      <td><%= link_to 'Show', wash %></td>
      <td><%= link_to 'Edit', edit_wash_path(wash) %></td>
      <td><%= link_to 'Destroy', wash, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>
    <div class="flickr_pagination">
      <%= will_paginate @washes, :container => true %>
      <div class='page_info'>(<%= page_entries_info @washes %>)</div>
     </div>
  <br />

  <%= link_to t(:new_wash), new_wash_path %>
</div> <!-- id=list -->

app/views/washes/new.html.erb
<div  class="container_12" role="main">
  <div class="grid_12">

<h1><%= t(:new_wash)%></h1>

<%= render 'newform' %>

<%= link_to 'Back', washes_path %>
  </div> <!-- class=grid_12 -->
</div> <!-- id=main -->

app/views/washes/show.html.erb
<div id="main" class="container_12" role="main">
  <div class="grid_12">
    

<p id="notice"><%= notice %></p>

<table  style="vertical-align:top"><thead><tr> </tr></thead>
<tbody><tr><td>
<p>
  <b><%= t(:customer)%>:</b>
  <%= @wash.customer_id %>
</p>
  <b><%= t(:email)%>:</b>
  <%= @wash.email %>
</p>

<p>
  <b><%= t(:name)%>:</b>
  <%= @wash.name %>
</p>

<p>
  <b><%= t(:mobile)%>:</b>
  <%= @wash.mobile %>
</p>

<p>
  <b><%= t(:phone)%>:</b>
  <%= @wash.phone %>
</p>

<p>
  <b><%= t(:address)%>:</b>
  <%= @wash.address %>
</p>

<p>
  <b><%= t(:address2)%>:</b>
  <%= @wash.address2 %>
</p>
<p>
  <b><%= t(:updated_at)%>:</b>
  <%= @wash.updated_at %>
</p>
<p>
  <b><%= t(:created_at)%>:</b>
  <%= @wash.created_at %>
</p>

</td><td style="width:5em">&nbsp;&nbsp;
</td><td   style="vertical-align:top">
  <div>
    <div class="field" style="float:left;padding:1em">
      <%= label :wash, t(:stocked_on) %><br />
      <%= @wash.stocked_on %><br/>
      <span style="font-size:small;color:#aaa"><%= distance_of_time_in_words_to_now(@wash.stocked_on)%> 전</span>
    </div>
    <div class="field" style="float:left;padding:1em">
      <%= label :wash, t(:released_on) %><br />
      <%= @wash.released_on %>
    </div>
    <div class="field" style="float:left;padding:1em">
      <%= label :wash, t(:status) %><br />
      <%= @wash.status %>
    </div><br style="clear:both"/>
    <div class="field">
      <%= label :wash, t(:memo)%><br/>
      <%= text_area :wash, :memo, :cols=>50, :rows=>4, :readonly=>true %>
    </div>
  </div>
  <div id="list">
   <table><thead>
   <tr><th>&nbsp;</th><th><%= t(:unit_price) %></th> <th><%= t(:count) %></th>
   <th><%= t(:repair) %></th>  <th><%= t(:repair_price) %></th><th><%= t(:status) %></th>
   </tr>
   </thead>
   <tbody>
   <% wash_sum = 0; repair_sum = 0 %>
   <% @wash.cloths.each do | cloth |  %>
      <%  wash_sum += cloth.unit_price * cloth.count
              repair_sum += cloth.repair_price %>
   <tr><td class="right"><%= cloth.cloth_item.name %> </td>
     <td class="price" > <%=   number_with_delimiter( cloth.unit_price, :delimiter => ",")  %>원 </td>
   <td class="num"> <%= cloth.count  %>개 </td>
   <td style="width:220px">  <%= cloth.repair  %> </td>
   <td class="price">  <%= number_with_delimiter(  cloth.repair_price, :delimiter => ",")  %>원 </td>
    <td>  <%= cloth.status  %> </td>
   <% 	end # end of cloth %>
  </tr></tbody>
  <tfoot>
   <tr><td class="sum"> <%= t('wash_sum') %></td><td colspan="2" class="price"> <%= number_with_delimiter(wash_sum) %>원</td><td class="sum"><%= t'repair_sum'%></td><td class="price"><%= number_with_delimiter(repair_sum) %>원</td><td>&nbsp;</td>
   </tr>
     <tr><td class="sum"> <%= t('total') %></td><td colspan="2" class="right"></td><td></td><td class="price"><%= number_with_delimiter(wash_sum + repair_sum) %>원</td><td>&nbsp;</td>
     </tr>
   </tfoot>
   </table>      
</div> <!-- id=list -->
 
</td></tr>
</tbody>
</table>

<%= link_to 'Edit', edit_wash_path(@wash) %> |
<%= link_to 'Back', washes_path %>

  </div> <!-- class=grid_12 -->
</div> <!-- id=main -->