config/routes.rb
YouCloth::Application.routes.draw do

  namespace :admin do 
    resources :dashboard
    resources :posts  do
      resources :comments do
        post :reply, :on => :member
      end
    end
  end

   match "you/washes/:id" => 'you#show', as: "you_washes"
   match 'you' => 'you#index'
  scope "/you" do
      resources :posts
   end

  resources :posts do
    resources :comments do
      post :reply
    end
  end

  resources :customers  do
    collection do
      get :users
      get :new_popup
      post :create_popup
    end
  end

  resources :washes do
    collection do
      get :customers
    end
  end

  resources :cloth_items

  resources :cloths

  resources :roles

  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" },
                      :path_names => { :sign_up => "register", 
                                      :sign_in => "login", 
                                      :sign_out => "logout",
                                      :settings => "settings" }
  devise_scope :user do
    post :change_customer, :to => "users/registrations#change_customer"
    put :change_customer, :to => "users/registrations#change_customer"
  end

  

  root :to => "home#index"
  

end

app/controllers/you_controller.rb
class YouController < ApplicationController
  before_filter :authenticate_user!	
  #filter_resource_access
  def index
    q = params[:q]
    field = params[:field]
    #logger.debug ">> field: #{field}"
    if q.blank?
      @washes = Wash.where('email = ?', current_user.email).paginate(:page => params[:page]).order('stocked_on DESC, id ASC')
    else
      q.strip!
      field.strip!
      @washes = case field.to_sym
                when :name
                  Wash.where(" email = ? AND LOWER(name) LIKE ? ", current_user.email, "%#{q.downcase}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                 when :email
                  Wash.where(" email = ? AND LOWER(email) LIKE ? ", current_user.email, "%#{q.downcase}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                 when :phone
                  Wash.where("email = ? AND (phone LIKE ? OR mobile LIKE ?) ", current_user.email, "%#{q}%", "%#{q}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                when :address
                  Wash.where("email = ? AND (LOWER(address) LIKE ? OR LOWER(address2) LIKE ?) ", current_user.email, "%#{q.downcase}%", "%#{q.downcase}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                when :stocked_on
                  Wash.where("email = ? AND stocked_on LIKE ? ", current_user.email, "%#{q}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                 when :released_on
                  Wash.where("email = ? AND released_on LIKE ? ", current_user.email, "%#{q}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                when :status
                  Wash.where("email = ? AND LOWER(status) LIKE ? ", current_user.email, "%#{q.downcase}%").paginate(:page => params[:page]).order('stocked_on DESC, created_at ASC')
                else #all
                  where = <<-DOCUMENT
                    email = ? AND (LOWER(name) LIKE ? OR LOWER(email) LIKE ? 
                    OR phone LIKE ? OR mobile LIKE ? 
                    OR LOWER(address) LIKE ? OR LOWER(address2) LIKE ?  
                    OR LOWER(status) LIKE ?)  
                  DOCUMENT

                  Wash.where( where, current_user.email, "%#{q.downcase}%", "%#{q.downcase}%", "%#{q}%", "%#{q}%", "%#{q.downcase}%", "%#{q.downcase}%", "%#{q.downcase}%").paginate(:page => params[:page]).order('stocked_on DESC, id ASC')
                end
    end #end of if
    #@show_pagination = @washes.length > 0 && @washes.total_pages > 1
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @washes }
    end
  end

  def show
     #@wash = Wash.includes(:cloths).joins(:customer).where("washes.id = ? AND customers.user_id = ?", params[:id], current_user.id)
     @wash = Wash.joins(:customer).where("customers.user_id =?", current_user.id).find(params[:id])
     #@wash =  Wash.find_by_sql("SELECT `washes`.* FROM `washes` LEFT OUTER JOIN `customers` ON `customers`.`id` = `washes`.`customer_id` WHERE (washes.id = '38' AND customers.user_id = 34) LIMIT 1")
    respond_to do |format|
      format.html # sExtractedExtractedhow.html.erb
      format.json { render json: @wash }
    end
  end

  def profile
  end

  # def posts
  #  @posts = Post.includes(:user).where("user_id =?", current_user.id).paginate(page: params[:page]).order(" updated_at DESC")
  # end

end

app/helpers/you_helper.rb
module YouHelper
end

app/views/you/index.html.erb
  <div id="list">
  <%= form_tag you_path, :method => :get  do %>
    <div class="field">
    <%= label :wash, :search %><br/>
    <%= select_tag 'field', options_for_select(YouCloth::WASH_SEARCH_FIELD, params[:field]) %> 
    <%= text_field_tag 'q', params[:q] %> 
    <%= submit_tag t('find') %>
    </div>
  <% end %>

  <h1>Your washes</h1>

    <div class="flickr_pagination">
      <%= will_paginate @washes, :container => false %>
      <div class='page_info'>(<%= page_entries_info @washes %>)</div>
    </div>

  <table>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Mobile/<br/>
          Phone</th>
      <th>Address</th>
      <th>Address2</th>
      <th>Stocked on</th>
      <th>Released on</th>
      <th>Status</th>
      <th></th>
    </tr>

  <% @washes.each do |wash| %>
    <tr>
      <td><%= wash.id %></td>
      <td><%= wash.name %></td>
      <td><%= wash.email %></td>
      <td><%= wash.mobile %>/<br/>
          <%= wash.phone %></td>
      <td><%= wash.address %></td>
      <td><%= wash.address2 %></td>
      <td><%= wash.stocked_on %><br/>
          <span style="font-size:small;color:#aaa"><%= distance_of_time_in_words_to_now(wash.stocked_on)%> 전</span></td>
      <td><%= wash.released_on %></td>
      <td><%= wash.status %></td>
      <td><%= link_to 'Show', "/you/washes/#{wash.id}" %></td>
    </tr>
  <% end %>
  </table>
    <div class="flickr_pagination">
      <%= will_paginate @washes, :container => true %>
      <div class='page_info'>(<%= page_entries_info @washes %>)</div>
     </div>
  <br />
</div> <!-- id=list -->

app/views/you/posts.html.erb
  <div id="list">
  <%= form_tag posts_path, :method => :get  do %>
    <div class="field">
    <%= label :post, :search %><br/>
    <%= select_tag 'field', options_for_select(YouCloth::WASH_SEARCH_FIELD, params[:field]) %> 
    <%= text_field_tag 'q', params[:q] %> 
    <%= submit_tag t('find') %>
    </div>
  <% end %>

  <h1>Listing posts</h1>
   <%= link_to 'New Message', new_post_path %>

    <div class="flickr_pagination">
      <%= will_paginate @posts, :container => false %>
      <div class='page_info'>(<%= page_entries_info @posts %>)</div>
    </div>

  <table>
    <tr>
      <th>Id</th>
      <th><b>Title</b><br/>
        Subject</th>
       <th>Updated at</th>
   <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.id %></td>
      <td><b><%=link_to post.title,  post_comments_path( post)%></b><br/>
        <%=link_to post.subject, post_comments_path( post) %></td>
     <td><%= post.updated_at %><br/>
          <span style="font-size:small;color:#aaa"><%= distance_of_time_in_words_to_now(post.updated_at)%> 전
            by <%= post.user.email %>
          </span></td>
      <td><%= link_to 'Show', post_comments_path( post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>
    <div class="flickr_pagination">
      <%= will_paginate @posts, :container => true %>
      <div class='page_info'>(<%= page_entries_info @posts %>)</div>
     </div>
  <br />

  <%= link_to 'New Message', new_post_path %>
</div> <!-- id=list -->

app/views/you/profile.html.erb
<h1>You#profile</h1>
<p>Find me in app/views/you/profile.html.erb</p>

app/views/you/show.html.erb
<div id="main" class="container_12" role="main">
  <div class="grid_12">
    

<p id="notice"><%= notice %></p>

<table  style="vertical-align:top"><thead><tr> </tr></thead>
<tbody><tr><td>
<p>
  <b><%= t(:customer)%>:</b>
  <%= @wash.customer_id %>
</p>
  <b><%= t(:email)%>:</b>
  <%= @wash.email %>
</p>

<p>
  <b><%= t(:name)%>:</b>
  <%= @wash.name %>
</p>

<p>
  <b><%= t(:mobile)%>:</b>
  <%= @wash.mobile %>
</p>

<p>
  <b><%= t(:phone)%>:</b>
  <%= @wash.phone %>
</p>

<p>
  <b><%= t(:address)%>:</b>
  <%= @wash.address %>
</p>

<p>
  <b><%= t(:address2)%>:</b>
  <%= @wash.address2 %>
</p>
<p>
  <b><%= t(:updated_at)%>:</b>
  <%= @wash.updated_at %>
</p>
<p>
  <b><%= t(:created_at)%>:</b>
  <%= @wash.created_at %>
</p>

</td><td style="width:5em">&nbsp;&nbsp;
</td><td   style="vertical-align:top">
  <div>
    <div class="field" style="float:left;padding:1em">
      <%= label :wash, t(:stocked_on) %><br />
      <%= @wash.stocked_on %><br/>
      <span style="font-size:small;color:#aaa"><%= distance_of_time_in_words_to_now(@wash.stocked_on)%> 전</span>
    </div>
    <div class="field" style="float:left;padding:1em">
      <%= label :wash, t(:released_on) %><br />
      <%= @wash.released_on %>
    </div>
    <div class="field" style="float:left;padding:1em">
      <%= label :wash, t(:status) %><br />
      <%= @wash.status %>
    </div><br style="clear:both"/>
  </div>
  <div id="list">
   <table><thead>
   <tr><th>&nbsp;</th><th><%= t(:unit_price) %></th> <th><%= t(:count) %></th>
   <th><%= t(:repair) %></th>  <th><%= t(:repair_price) %></th><th><%= t(:status) %></th>
   </tr>
   </thead>
   <tbody>
   <% wash_sum = 0; repair_sum = 0 %>
   <% @wash.cloths.each do | cloth |  %>
      <%  wash_sum += cloth.unit_price * cloth.count
              repair_sum += cloth.repair_price %>
   <tr><td class="right"><%= cloth.cloth_item.name %> </td>
     <td class="price" > <%=   number_with_delimiter( cloth.unit_price, :delimiter => ",")  %>원 </td>
   <td class="num"> <%= cloth.count  %>개 </td>
   <td style="width:220px">  <%= cloth.repair  %> </td>
   <td class="price">  <%= number_with_delimiter(  cloth.repair_price, :delimiter => ",")  %>원 </td>
    <td>  <%= cloth.status  %> </td>
   <% 	end # end of cloth %>
  </tr></tbody>
  <tfoot>
   <tr><td class="sum"> <%= t('wash_sum') %></td><td colspan="2" class="price"> <%= number_with_delimiter(wash_sum) %>원</td><td class="sum"><%= t'repair_sum'%></td><td class="price"><%= number_with_delimiter(repair_sum) %>원</td><td>&nbsp;</td>
   </tr>
     <tr><td class="sum"> <%= t('total') %></td><td colspan="2" class="right"></td><td></td><td class="price"><%= number_with_delimiter(wash_sum + repair_sum) %>원</td><td>&nbsp;</td>
     </tr>
   </tfoot>
   </table>      
</div> <!-- id=list -->
<br/>
<%= link_to 'Back', you_path %>
</td></tr>
</tbody>
</table>


  </div> <!-- class=grid_12 -->
</div> <!-- id=main -->